### ISSUE TITLE
解压失败

### ISSUE THREAD

**Issue by tuzi66** [zsnmwy/ArchiSteamFarm-Install-Script#10]
![tim 20180723102621](https://user-images.githubusercontent.com/38389617/43054183-dc2699d8-8e62-11e8-86f7-8226211fffcf.png)
解压失败怎么解决呀

**Comment by zsnmwy** [comment]
嗯？你是执行那里的脚本的？

这个是老脚本才会出现的问题，这个我已经修了

看这个wiki

https://github.com/zsnmwy/ArchiSteamFarm-Install-Script/wiki/v2.0-%E6%8C%87%E5%8D%97

**Comment by tuzi66** [comment]
我用的stenmcn的那个 😅

**Comment by zsnmwy** [comment]
steamcn的那个，我不是已经标出来了吗，，，

以这个wiki为准啊。。

看来我得把之前安装脚本的地址给去掉才行。

**Comment by zsnmwy** [comment]
应该可以了吧，没有什么问题，我就关掉issues了

**Comment by tuzi66** [comment]
pm2输入不了密码呀

**Comment by zsnmwy** [comment]
是输不了的。死活要你输，就用screen。

先移除任务

```
asf -r
```

再用screen 

```
asf -scr
```

**Comment by tuzi66** [comment]
输入不了 会显示无账号运行 😭

**Comment by zsnmwy** [comment]
PM2的log查看是不提供TTY交互的。
ASF那边要你输密码，或者令牌。一旦没有交互，就会报错。

你pm2 用不了，就用screen咯.


```
asf -scr
```
这就是用screen来启动ASF的。

**Comment by tuzi66** [comment]
那我想知道你是怎么登陆的呢？

**Comment by zsnmwy** [comment]
我？ 

1. 用脚本安装完ASF之后，会自动启动ASF，然后就输密码。正常了就停止。
1. 然后把令牌导入到ASF。
1. 直接`asf -bg`，把ASF丢到PM2里面去管理。



令牌导入了，就不用输密码，也不用输入令牌。

然后就没有我啥事了。

**Comment by tuzi66** [comment]
哦

**Comment by zsnmwy** [comment]
所以你还有什么问题吗？  
没有我就关掉issues了

**Comment by tuzi66** [comment]
好了

![default](https://user-images.githubusercontent.com/38389617/43061222-f2389d24-8e86-11e8-8634-c2f3607425b2.PNG)
