### ISSUE TITLE
Fail --- ASF connect to Steam

### ISSUE THREAD

**Issue by hdfskycat** [zsnmwy/ArchiSteamFarm-Install-Script#12]
- Make sure the script support for your system.If .NET Core 2.0 support for your system,but the script is not.Please tell me ,I will support for your system in the future.  

[Script - Supported OS Versions](https://github.com/zsnmwy/ArchiSteamFarm-Install-Script/wiki/%E7%8E%B0%E5%9C%A8%E6%94%AF%E6%8C%81%E7%9A%84%E7%B3%BB%E7%BB%9F---System-support-ever)

[.NET Core 2.0 - Supported OS versions](https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0-supported-os.md)

---

- Your OS Version

---

- Script Version

---

- Error

**Comment by zsnmwy** [comment]
Do you have any questions?

你有啥问题？

**Comment by hdfskycat** [comment]
2018-09-22 21:13:30|dotnet-17905|INFO|*******|OnDisconnected() 从Steam断开连接！
2018-09-22 21:13:30|dotnet-17905|INFO|*******|OnDisconnected() 超过频率限制，我们将在 25 分 分钟后重试……

**Comment by zsnmwy** [comment]
你的主机是在国内还是在国外的？

**Comment by hdfskycat** [comment]
阿里新加坡

**Comment by zsnmwy** [comment]
把日志截全一点，还有你没有装了ssr这类东西。

检查你的防火墙，安全组。

还有你这个问题是ASF的本身问题，跟我脚本无关啊emmmm

**Comment by hdfskycat** [comment]
好的，我再检查下，我的系统是重新DD过的，不知道有没有关系，感谢回复！
