### ISSUE TITLE
七牛云源已被弃用

### ISSUE THREAD

**Issue by zsnmwy** [zsnmwy/ArchiSteamFarm-Install-Script#14]
@Lunaeth

七牛云源早已经弃用了。

七牛云是之前旧版本用的，现在都只用github的了。

请问你的在哪里看到的？

我去改掉他。=。=

最新的版本在[这里](https://github.com/zsnmwy/ArchiSteamFarm-Install-Script/blob/master/install.sh)。

**Comment by Lunaeth** [comment]
https://www.jianshu.com/p/71a02c07705b
