### ISSUE TITLE
debian7安装失败。

### ISSUE THREAD

**Issue by ghost** [zsnmwy/ArchiSteamFarm-Install-Script#6]
[信息]  你的选择是(数字): 
1
[OK]  当前用户是root用户，进入安装流程  
[OK]  符合脚本的系统位数要求 64位 
[信息]  未安装ArchiSteamFarm  
[信息]  准备安装ArchiSteamFarm 
[信息]  国内机子要启用，国外机子不用管 
[信息]  是否启用七牛云源?[Y/n] 
(默认: N):n
[信息]  不使用七牛云源 
debian
7
[错误]  当前系统为 debian 7 不在支持的系统列表内，安装中断

**Comment by zsnmwy** [comment]
debian7 不在脚本的支持范围内

不支持的原因：微软在.NET Core 2.0 上不支持Debian7

https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0-supported-os.md

---

## 现在支持的系统 / System support ever

Raspberry Pi 2/3
```
Raspian 9
```
---

Only support for x64

Debian

    Debian8 x64
    Debian9 x64

Centos

    Centos7 x64

Ubuntu

    Ubuntu 17.10 x64
    Ubuntu 17.04 x64
    Ubuntu 16 x64
    Ubuntu 14 x64
