### ISSUE TITLE
ipc无法启动

### ISSUE THREAD

**Issue by allenleeok** [zsnmwy/ArchiSteamFarm-Install-Script#7]
按照说明一步步进行，但是打开浏览器输入带端口的ip地址并不能访问，看日志，貌似server并没有启动，是不是命令没有生效

**Comment by zsnmwy** [comment]
现在ASF启动IPC的方式已经改了，但是我的脚本并没有更新。。。

SO。。。

你可以去ASF那边去看看他们的WIKI。

**Comment by allenleeok** [comment]
AFS.json里添加"IPC": true就ok了，还有wiki对ipc密码设置的描述也有问题，设置密码需要用引号来表示在其中的密码

**Comment by zsnmwy** [comment]
https://github.com/zsnmwy/ArchiSteamFarm-Install-Script/issues/9
