### ISSUE TITLE
请求支持Ubuntu18.04

### ISSUE THREAD

**Issue by kzw200015** [zsnmwy/ArchiSteamFarm-Install-Script#9]
- Make sure the script support for your system.If .NET Core 2.0 support for your system,but the script is not.Please tell me ,I will support for your system in the future.  

[Script - Supported OS Versions](https://github.com/zsnmwy/ArchiSteamFarm-Install-Script/wiki/%E7%8E%B0%E5%9C%A8%E6%94%AF%E6%8C%81%E7%9A%84%E7%B3%BB%E7%BB%9F---System-support-ever)

[.NET Core 2.0 - Supported OS versions](https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0-supported-os.md)

---

- Your OS Version

---

- Script Version

---

- Error

**Comment by zsnmwy** [comment]
看下标题，中文。

emmmm 应该是国人。

~~懒得show出我蹩脚的英语。~~

这ASF脚本我从写了一次。刚刚完工。

Readme里面的描述还没有更新。

脚本里面的英语描述也没有完工。看得懂中文就无关紧要。

---

Ubuntu 18.04 x64 我已经增加了支持。

---

root用户执行下面的命令

```
wget https://raw.githubusercontent.com/zsnmwy/ArchiSteamFarm-Install-Script/master/install.sh && bash install.sh
```

---

如果没有出错，装完之后就会直接启动asf，并且让你输入密码。

输入密码，之后，确认asf 正常运行。就`Ctrl + c`终止他

可以选择用`screen`或者`pm2`后台。

推荐PM2

---

```
使用方法
	asf
		==========asf启动方式=========================
		-s      | --start       正常启动，不后台
		-scr    | --screen      在screen内启动asf，不会检测任务是否存在
		==========PM2管理asf快捷选项===================
		-bg     | --background  把asf丢到PM2里面后台，可自动重启asf(推荐)
		-l      | --log         列出日志
		-r      | --remove      从PM2中移除asf任务
		-st     | --status      查看当前asf的状态
		==========IPC相关快速设置项====================
		-ipc    |               是否启用IPC
		-c      |               更改IPC密码
		-C      |               更改IPC端口号
		==========steam 账号管理====================
		-acc    | --account     steam 账号管理
```

---

如果有任何问题或者成功，请回复下。

Thanks.

**Comment by kzw200015** [comment]
在你回复我之前这段时间，我自己折腾好了，23333，没法测试了，抱歉

**Comment by zsnmwy** [comment]
好的🤣
